#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p mitmf /usr/share/mitmf
fi
echo "-------------------------------------------------"
echo "To finish the installation u need to run this"
echo "pip install twisted requests NetfilterQueue scapy msgpack dnspython configobj pillow pefile configobj"
echo "-------------------------------------------------"

# End automatically added section
